### ISSUE TITLE
Error loading package

### ISSUE THREAD

**Issue by cdevoe57** [JustinAzoff/can-i-use-afpacket-fanout#1]
I'm attempting to install this and run it on a system Running Oracle Linux (red hat)
Linux server.x.y 4.1.12-61.1.25.el6uek.x86_64 #2 SMP Wed Jan 11 19:13:03 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
I get the following error.    

go get github.com/JustinAzoff/can-i-use-afpacket-fanout
# github.com/google/gopacket/afpacket
could not determine kind of name for C.sizeof_struct_tpacket3_hdr

**Comment by JustinAzoff** [comment]
ah.. that's a RHEL6 based system.  I don't think af_packet will work at all on such a system.

**Comment by cdevoe57** [comment]
Yes, but the kernel is 4.1.12 which supports af_packet.

**Comment by JustinAzoff** [comment]
Hmm.  The tpacket3_hdr struct is supposed to be defined in the linux/if_packet.h header file.

According to https://github.com/google/gopacket/issues/149 you just need >= 3.1.

I think the problem may be a discrepancy between the headers in /usr/include/linux and the headers that are part of the linux kernel you have.. or possibly you are missing the kernel-headers package for the 4.1.12 kernel?  How many if_packet.h files does your system have?

**Comment by cdevoe57** [comment]
So it does appear to be an issue with the incorrect headers.  Which I am now trying to figure out why when I update the kernel are the header files not also updated.

**Comment by JustinAzoff** [comment]
I built and released some binaries, which should work on centos6:
```
$ docker run -t -i --rm centos:6
[root@1267443a2ee5 /]# rpm -ivh https://github.com/JustinAzoff/can-i-use-afpacket-fanout/releases/download/v1.0/can-i-use-afpacket-fanout_1.0_linux_amd64.rpm
Retrieving https://github.com/JustinAzoff/can-i-use-afpacket-fanout/releases/download/v1.0/can-i-use-afpacket-fanout_1.0_linux_amd64.rpm
Preparing...                ########################################### [100%]
   1:can-i-use-afpacket-fano########################################### [100%]
[root@1267443a2ee5 /]# can-i-use-afpacket-fanout -h
Usage of can-i-use-afpacket-fanout:
```

otherwise I don't think I can do anything about this issue.. If anything it's an issue with the afpacket stuff in gopacket and would have to be fixed there.
